export {
  Refresh as RetryIcon,
  Delete as DeleteIcon,
  Edit as UpdateIcon,
  ChatBubbleOutline as CommentIcon,
  ChatBubble as CommentIconFilled,
  Whatshot as FlameIcon,
  ArrowDropDown as DropDownIcon,
  LocalMall as ShopIcon,
  Telegram as MessengerIcon,
  KeyboardArrowUpRounded as ArrowUpIcon,
  AddAPhotoRounded as CameraIcon,
  CheckCircleOutlineOutlined as CheckIcon,
  Error as ErrorIcon,
  SettingsRounded as SettingsIcon,
  ExitToAppRounded as LogoutIcon,
  Brightness4Rounded as SunIcon, // DarkMode icon available in MUI5
  SecurityRounded as SecurityIcon,
  ContactSupportRounded as ContactIcon,
  MoreVert as MoreVertIcon,
  Cake as BirthdayIcon,
  Flare as BioIcon,
  Language as WebsiteIcon,
  LocationOn as LocationIcon,
  Wc as GenderIcon,
  Public as PublicIcon,
  Lock as PrivateIcon,
  Apps as ImageGridIcon,
  PersonAdd as FollowedIcon,
  FiberManualRecordTwoTone as CircleIcon,
  FiberManualRecordSharp as CircleIconFilled,
} from '@material-ui/icons';

export { FcGoogle as GoogleIcon } from 'react-icons/fc';
export { FaFacebook as FacebookIcon } from 'react-icons/fa';
